#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Oct 07 00:37:03 +08 2024
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim test_MCycle_behav -key {Behavioral:sim_1:Functional:test_MCycle} -tclbatch test_MCycle.tcl -log simulate.log"
xsim test_MCycle_behav -key {Behavioral:sim_1:Functional:test_MCycle} -tclbatch test_MCycle.tcl -log simulate.log

